###
POST http://localhost:3001/api/sessions
Content-Type: application/json

{
    "username": "test1",
    "password": "pwd1"
}

###
GET http://localhost:3001/api/sessions/current

###
DELETE http://localhost:3001/api/sessions/current

###
GET http://localhost:3001/api/memes/single

###
GET http://localhost:3001/api/memes/match

###
GET http://localhost:3001/api/memes/12/captions

###
POST http://localhost:3001/api/matches
Content-Type: application/json

[
	{	
		"roundId": 1,
		"memeId": 2,
		"name": "meme2.png",
		"guessed": false
	},
	{
		"roundId": 2,
		"memeId": 4,
		"name": "meme4.png",
		"guessed": false
	},
	{
		"roundId": 3,
		"memeId": 3,
		"name": "meme3.png",
		"guessed": true
	}
]

###
GET http://localhost:3001/api/matches/history